// Cart
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

// WishList
const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

//Address
const ADD_ADDRESS = 'ADD_ADDRESS';
const REMOVE_ADDRESS = 'REMOVE_ADDRESS';

//Orders
const ADD_ORDERS = 'ADD_ORDERS';
const REMOVE_ORDERS = 'REMOVE_ORDERS';

export { 
    ADD_TO_CART, 
    REMOVE_FROM_CART, 
    ADD_TO_WISHLIST, 
    REMOVE_FROM_WISHLIST,
    ADD_ADDRESS,
    REMOVE_ADDRESS,
    ADD_ORDERS,
    REMOVE_ORDERS
} 